#' @title simData
#' simulate Data with orthogonal feature clusters
#' each feature cluster contains 10 features and corresponds to a different
#' orthogonal latent factor
#'
#' @param samples number of samples to generate
#' @param latent_factors number of latent factors to generate
#' @param replicates number of replicates to generate
#' @param error variance of the sampled noise
#'
#' @return array containing the simulated data with dimensions
#' samples x replicates x features
#'
#' @export
#'
#' @examples
#' # simulate data with 100 samples, 20 features generated by 2 latent factors
#' # and 2 replicates
#' simData(100,2,2)
simData <- function(samples,latent_factors, replicates, error=0) {
    # total number of features
    p <- latent_factors*10
    # sample target feature clusters from
    # standard multivariate normal distribution
    m <- rep(10, latent_factors)
    # randomly sample targetcluster vectors
    target <- MASS::mvrnorm(samples, mu= m, diag(rep(1, latent_factors)))
    # store magnitude of vector
    mag <- sqrt(colSums(target^2))
    # orthonormalize the vectors
    gs <- pracma::gramSchmidt(target)
    target <- gs$Q
    # rescale orthonormal vectors to original size
    target <- t(t(target) *mag)

    numfeat <- 10*latent_factors
    base <- array(dim = c(samples, numfeat))

    # generate 9 additional linearly dependent features
    # for each feature cluster
    for (i in seq_len(latent_factors)){
        base[,(i-1)*10+1] <- target[,i]
        for (j in seq_len(9)){
            coefs <- stats::rnorm(1)
            # add noise to reduce orthogonality between features in same cluster
            base[,(i-1)*10+1+j] <- (abs(coefs) * target[,i]) +
                stats::rnorm(samples,0,error)
        }

    }
    # generate replicates and add noise
    replist <- list()
    if (replicates > 1) {
        for (i in seq_len(replicates)) {
            # add different noise to each replicate and concatenate
            noise <- array(stats::rnorm(nrow(base) * ncol(base), mean = 0,
                            sd =0.5),dim(base))
            if (i == 1){
                rep <- base
            } else {
                rep <- base + noise
            }
            replist[[i]] <- rep
        }
        # combine replicates
        data <- Reduce(function(x,y) abind::abind(x,y,along=3), replist)
    } else {
        # generate only 1 replicate if replicates == 1
        noise <- array(stats::rnorm(nrow(base) * ncol(base), mean = 0, sd = 0.5),
                       dim(base))
        data <- base + noise
    }
    featnames <- c()
    for(i in seq_len(latent_factors)){
        featnames <- c(featnames, paste0("Latent_factor",i,"_Feature", seq_len(10)))
    }
    dimnames(data)[[2]] <-  featnames
    data
}
